language: ruby
rvm:
- 2.5
sudo: required
dist: xenial
before_install:
  - sudo apt-get install -y advancecomp gifsicle optipng pngcrush pngquant
  - gem install image_optim
  - image_optim --no-svgo --no-pngout --no-jhead --no-jpegoptim --no-jpegtran -r img/*.png
script:
  - bundle exec jekyll build
  - sed -i 's/\.html//' _site/sitemap.xml
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
