language: ruby
rvm:
- 2.5
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush pngquant
  - gem install image_optim
  - image_optim --no-svgo -r img/*.png
script: "bundle exec jekyll build"
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
