navigation:
  - title: 'Home'
    url: ''

  - title: 'Hardware'
    url: 'hardware/'

  - title: 'Software'
    url: 'software/'

  - title: 'About'
    url: 'about/'

footer:
  - title:
      en: 'Imprint'
      de: 'Impressum'
    url: 'imprint.html'
  - title:
      en: 'Press'
      de: 'Presse'
    url: 'press.html'
  - title:
      en: 'Jobs'
      de: 'Jobs'
    url: 'jobs.html'
  - title:
      en: 'Blog'
      de: 'Blog'
    full_url: 'https://blog.touchlay.com'

footertitle:
  en: 'Interested? Contact us!'
  de: 'Interessiert? Kontaktieren Sie uns!'

interessts:
  en:
    - nova
    - rent
    - buy
    - project
    - software
    - cluud
  de:
    - nova
    - mieten
    - kaufen
    - projekt
    - software
    - cluud

interesstsplaceholder:
  en: 'interested in...'
  de: 'Interessiert an...'

countryplaceholder:
  en: 'country'
  de: 'Land'

texts:
  more:
    en: 'learn more'
    de: 'mehr erfahren'
  playvideo:
    en: 'play video'
    de: 'Video abspielen'
  subscribe:
    en: 'subscribe'
    de: 'anmelden'
  send:
    en: 'send'
    de: 'senden'
  email:
    en: 'email'
    de: 'E-Mail'
  phone:
    en: 'phone'
    de: 'Telefon'
  address:
    en: 'address'
    de: 'Adresse'
  austria:
    en: 'Austria'
    de: 'Österreich'
  name:
    en: 'name'
    de: 'Name'
  message:
    en: 'message (optional)'
    de: 'Nachricht (optional)'
  requestnewsletter:
    en: 'subscribe to newsletter'
    de: 'Newsletter erhalten'
  requestprice:
    en: "request pricing"
    de: "Preise anfragen"
  contactsuccess:
    en: '✔ Received inquiry - thank you! :)'
    de: '✔ Anfrage erhalten - danke! :)'
  contacterror:
    en: '❌ Could not send your request, please contact us at <a href="mailto:hello@touchlay.com">hello@touchlay.com</a>.'
    de: '❌ Wir konnten Ihre Anfrage nicht senden, bitte kontaktieren Sie uns unter <a href="mailto:hello@touchlay.com">hello@touchlay.com</a>.'

newsletter:
  headline:
    en: Stay up to date
    de: Bleiben Sie am letzten Stand
  description:
    en: 'Receive special offers, information about new products, <br />and tips and tricks to impress your customers.'
    de: 'Erhalten Sie Information über Sonderangebote, neue Produkte, <br />sowie Tips und Tricks um Ihre Kunden zu begeistern.'

cookie:
  description:
    en: "This website uses cookies to ensure you get the best experience on our website."
    de: "Diese Webseite verwendet Cookies. Durch das Nutzen dieser Seite sind Sie mit der Verwendung von Cookies einverstanden."
  more:
    en: "Learn more"
    de: "Mehr Information"
  accept:
    en: "got it!"
    de: "ok!"
